import jsPDF from 'jspdf';
import { format } from 'date-fns';
import { dataService } from '@/services/dataService';
import { getDayTotals } from '@/store/selectors';
import type { Baby } from '@/types/events';

export async function exportDaySummaryPDF(baby: Baby, date: Date) {
  const dayISO = format(date, 'yyyy-MM-dd');
  const events = await dataService.listEventsByDay(baby.id, dayISO);
  const totals = getDayTotals(events);

  // Create PDF
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(20);
  doc.text('Nestling Daily Summary', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Baby name and date
  doc.setFontSize(14);
  doc.text(`Baby: ${baby.name}`, 20, y);
  y += 8;
  doc.text(`Date: ${format(date, 'EEEE, MMMM d, yyyy')}`, 20, y);
  y += 15;

  // Summary section
  doc.setFontSize(16);
  doc.text('Daily Summary', 20, y);
  y += 10;

  doc.setFontSize(12);
  doc.text(`Total Feeds: ${totals.feedCount}`, 20, y);
  y += 7;
  if (totals.totalMl > 0) {
    doc.text(`Total Milk: ${totals.totalMl} ml`, 20, y);
    y += 7;
  }

  const sleepHours = Math.floor(totals.sleepMinutes / 60);
  const sleepMins = totals.sleepMinutes % 60;
  doc.text(`Total Sleep: ${sleepHours}h ${sleepMins}m (${totals.sleepCount} naps)`, 20, y);
  y += 7;

  doc.text(
    `Diapers: ${totals.diaperTotal} (💧${totals.diaperWet} 💩${totals.diaperDirty})`,
    20,
    y
  );
  y += 15;

  // Last feed and sleep
  const lastFeed = events
    .filter((e) => e.type === 'feed')
    .sort((a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime())[0];

  const lastSleep = events
    .filter((e) => e.type === 'sleep')
    .sort((a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime())[0];

  if (lastFeed) {
    doc.text(`Last Feed: ${format(new Date(lastFeed.startTime), 'h:mm a')}`, 20, y);
    y += 7;
  }

  if (lastSleep && lastSleep.endTime) {
    doc.text(`Last Wake: ${format(new Date(lastSleep.endTime), 'h:mm a')}`, 20, y);
    y += 15;
  }

  // Timeline section
  if (events.length > 0) {
    doc.setFontSize(16);
    doc.text('Timeline', 20, y);
    y += 10;

    doc.setFontSize(10);
    const sortedEvents = [...events].sort(
      (a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime()
    );

    for (const event of sortedEvents.slice(0, 15)) {
      // Limit to 15 events to fit on page
      if (y > 270) break; // Don't overflow page

      const time = format(new Date(event.startTime), 'h:mm a');
      const type = event.type.charAt(0).toUpperCase() + event.type.slice(1);
      const subtype = event.subtype ? ` (${event.subtype})` : '';

      doc.text(`${time} - ${type}${subtype}`, 20, y);
      y += 6;
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.text(
    'Generated by Nestling - This is not medical advice',
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  );

  // Save PDF
  doc.save(`nestling-summary-${baby.name}-${dayISO}.pdf`);
}
