# SwiftLint Configuration for Nestling iOS App
# https://github.com/realm/SwiftLint

disabled_rules:
  - trailing_whitespace
  - vertical_whitespace

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - computed_accessors_order
  - contains_over_first_not_nil
  - control_statement
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - orphaned_doc_comment
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - trailing_closure
  - type_contents_order
  - type_name
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher

excluded:
  - Carthage
  - Pods
  - build/
  - .build/
  - dist/
  - node_modules/
  - vendor/

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 2
  max_length: 50
  excluded:
    - iPhone
    - iPad
    - iOS
    - URL
    - ID
    - UUID

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - URL
    - ID
    - UUID
    - x
    - y
    - z

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 4
    error: 6

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
