# SwiftLint Configuration for Nestling/Nuzzle iOS App
# https://github.com/realm/SwiftLint

# Disabled rules that conflict with project style
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - nesting
  - todo # We handle TODOs separately

# Enabled rules with custom configuration
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - unowned_variable_capture
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 15

# Custom rules for this project
custom_rules:
  # Discourage force unwrapping
  force_unwrapping:
    name: "Force Unwrapping"
    regex: "\\w+!"
    message: "Avoid force unwrapping. Use optional binding or guard statements instead."
    severity: warning

  # Prefer type imports for better performance
  type_import:
    name: "Type Import"
    regex: "^import (?!type)"
    message: "Consider using 'import type' for type-only imports to improve bundle size."
    severity: warning
    included: ".*\\.swift"

# Excluded files and directories
excluded:
  - Carthage
  - Pods
  - .build
  - .swiftpm
  - build/
  - dist/
  - node_modules/
  - ios/Nuzzle/.swiftpm/
  - ios/backup*/
  - "**/*.generated.swift"
  - "**/Generated/"
  - "**/*+CoreDataProperties.swift"
  - "**/*+CoreDataClass.swift"

# Included file types
included:
  - Sources
  - ios/Nuzzle
  - ios/Nestling
  - ios/Sources

# Reporter configuration
reporter: "xcode" # Xcode-compatible output
