#!/bin/bash
# Script to get device logs from Xcode

echo "=== Getting device logs ==="
echo ""
echo "Method 1: Xcode Console"
echo "1. In Xcode, press Cmd+Shift+Y to open Debug Area"
echo "2. Look for red error messages"
echo ""
echo "Method 2: Device Console (Terminal)"
echo "Run this command in another terminal:"
echo "xcrun simctl spawn booted log stream --predicate 'processImagePath contains \"App\"' --level debug"
echo ""
echo "Method 3: Safari Web Inspector (Best for Web Debugging)"
echo "1. Connect iPhone via USB"
echo "2. On Mac: Safari → Develop → [Your iPhone] → [App Name]"
echo "3. This shows full JavaScript console, network, and errors"
echo ""
echo "=== Common Issues to Check ==="
echo "- Look for 'Failed to load resource' errors"
echo "- Check for JavaScript syntax errors"
echo "- Verify Capacitor bridge initialized"
echo "- Check network requests (should use capacitor://localhost)"
